changed file ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,27 +1,68 @@
 name: Java CI
+
 on:
-  - push
-  - pull_request_target
+  push:
+  pull_request_target:
+
 jobs:
   build:
     runs-on: ubuntu-latest
+
+    services:
+      mysql:
+        image: mysql:5.7
+        env:
+          MYSQL_ROOT_PASSWORD: SQL-12soj5
+          MYSQL_DATABASE: test
+        ports:
+          - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=10
+
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{github.event.pull_request.head.ref}}
           repository: ${{github.event.pull_request.head.repo.full_name}}
+
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: maven
+
+      - name: Export DB Config Variables
+        run: |
+          echo "DB_URL=jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC" >> $GITHUB_ENV
+          echo "DB_USER=root" >> $GITHUB_ENV
+          echo "DB_PASS=root_password" >> $GITHUB_ENV
+
+      - name: Wait for MySQL to be available
+        run: |
+          for i in 1 2 3 4 5; do 
+            if nc -z 127.0.0.1 3306; then 
+              echo "MySQL is available!"
+              exit 0
+            fi
+            echo "Waiting for MySQL... (Try $i/5)"
+            sleep 5
+          done
+          echo "MySQL failed to start."
+          exit 1
+
       - name: Build with Maven
+
         run: mvn --batch-mode --update-snapshots -DskipTests=false verify
+
       - uses: mate-academy/auto-approve-action@v2
         if: ${{ github.event.pull_request && success() }}
         with:
           github-token: ${{ github.token }}
+
       - uses: mate-academy/auto-reject-action@v2
         if: ${{ github.event.pull_request && failure() }}
         with:
